spring:
  datasource:
    url: jdbc:postgresql://db-analytics:5432/db_galileo_analytics
    username: galileo_user
    password: galileo_pass_2025

services:
  lecture:
    url: http://lecture:8081
  ecriture:
    url: http://ecriture:8082

